name: PlatformIO CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions:
  contents: write  # Allows writing to repository contents, including creating releases

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [ wemos_d1_mini32 ]  # List other boards here if you want to build for multiple

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build project
        run: |
          platformio run --environment ${{ matrix.board }}

      # Compress the build output folder into raw-gps.zip
      - name: Archive Build Artifacts
        run: |
          zip -r raw-gps-build-${{ github.ref_name }}-v1.0.${{ github.run_number }}.zip .pio/build/wemos_d1_mini32

      - name: Determine Tag, Release Name, and Draft Status
        id: tag_name
        run: |
          if [[ "${{ github.ref }}" == refs/heads/main ]]; then
            echo "TAG_NAME=v1.0.${{ github.run_number }}" >> $GITHUB_ENV
            echo "RELEASE_NAME=Release v1.0.${{ github.run_number }}" >> $GITHUB_ENV
            echo "DRAFT=false" >> $GITHUB_ENV
          else
            echo "TAG_NAME=feature-${{ github.ref_name }}-v1.0.${{ github.run_number }}" >> $GITHUB_ENV
            echo "RELEASE_NAME=feature-${{ github.ref_name }}-v1.0.${{ github.run_number }}" >> $GITHUB_ENV
            echo "DRAFT=true" >> $GITHUB_ENV
          fi

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.RELEASE_NAME }}
          draft: ${{ env.DRAFT }}
          prerelease: false  # Optional: Set to true if needed for feature builds

      - name: Set Upload URL to Environment File
        if: ${{ steps.create_release.outputs.upload_url != '' }}
        run: echo "UPLOAD_URL=${{ steps.create_release.outputs.upload_url }}" >> $GITHUB_ENV

      - name: Upload Build Artifacts to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: "raw-gps-build-${{ github.ref_name }}-v1.0.${{ github.run_number }}.zip"
          asset_name: "raw-gps-build-${{ github.ref_name }}-v1.0.${{ github.run_number }}.zip"
          asset_content_type: application/zip
