name: PlatformIO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: [ wemos_d1_mini32 ]  # List other boards here if you want to build for multiple

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Build project
        run: |
          platformio run --environment ${{ matrix.board }}

      - name: Run Lint (Optional)
        run: |
          platformio check --environment ${{ matrix.board }}
